### ISSUE TITLE
wrong type of CreateUnitFromTable

### ISSUE THREAD

**Issue by takegine** [ModDota/TypeScriptDeclarations#11]
/**
         * Creates a DOTA unit by its dota_npc_units.txt name from a table of entity key
         * values and a position to spawn at.
         */
        declare function CreateUnitFromTable(arg1: object, arg2: Vector): object;

should be 

        declare function CreateUnitFromTable(arg1: object, arg2: Vector): CDOTA_BaseNPC;

**Comment by robincodex** [comment]
fixed https://github.com/ModDota/TypeScriptDeclarations/commit/1922b84e69642c4c41e03f4da661150d7c1e2f4e
