### ISSUE TITLE
PlayerUltimateStateOrTime_t  more 

### ISSUE THREAD

**Issue by takegine** [ModDota/TypeScriptDeclarations#12]
![image](https://user-images.githubusercontent.com/64788603/103655964-f940c580-4fa2-11eb-8823-6f577d6f75c9.png)
 PlayerUltimateStateOrTime_t  

PLAYER_ULTIMATE_STATE_NO_MANA
PLAYER_ULTIMATE_STATE_NOT_LEVELED
PLAYER_ULTIMATE_STATE_HIDDEN

**Comment by robincodex** [comment]
fixed https://github.com/ModDota/TypeScriptDeclarations/commit/1922b84e69642c4c41e03f4da661150d7c1e2f4e
