### ISSUE TITLE
Suggest change owner type to CBaseEntity for CreateParticle

### ISSUE THREAD

**Issue by robincodex** [ModDota/TypeScriptDeclarations#9]
https://github.com/ModDota/TypeScriptDeclarations/blob/d868467d2cbfc903da29ea27fc891a8c2b93d114/packages/dota-lua-types/types/api.generated.d.ts#L7910-L7936

I suggest that the owner type is `CBaseEntity`. `GameModeEntity`, `info_target`, `info_particle_system` are also effective. Similarly, the third parameter of `SetParticleControlEnt` may not necessarily be a unit, the entity `prop_dynamic` can be effective.

**Comment by DoctorGester** [comment]
@RobinCodeX you should make a pull request to https://github.com/ModDota/dota-data
